//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTH3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Congtrinh
    {
        public string MaCT { get; set; }
        public string TenCT { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<System.DateTime> NGAYCAPGP { get; set; }
        public Nullable<System.DateTime> NGAYKC { get; set; }
    }
}
