//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTH3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cong
    {
        public string MaCT { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> SLNgayCong { get; set; }
    }
}
