//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTH3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BTH3Entities : DbContext
    {
        public BTH3Entities()
            : base("name=BTH3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cong> Cong { get; set; }
        public virtual DbSet<Congtrinh> Congtrinh { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<Phongban> Phongban { get; set; }
    
        [DbFunction("BTH3Entities", "f_nvtheotuoi")]
        public virtual IQueryable<f_nvtheotuoi_Result> f_nvtheotuoi(Nullable<int> a, Nullable<int> b)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("b", b) :
                new ObjectParameter("b", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_nvtheotuoi_Result>("[BTH3Entities].[f_nvtheotuoi](@a, @b)", aParameter, bParameter);
        }
    
        [DbFunction("BTH3Entities", "F_NhanVienTheoDC")]
        public virtual IQueryable<F_NhanVienTheoDC_Result> F_NhanVienTheoDC(string diachi)
        {
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_NhanVienTheoDC_Result>("[BTH3Entities].[F_NhanVienTheoDC](@diachi)", diachiParameter);
        }
    
        [DbFunction("BTH3Entities", "F_NhanVienTheoMa")]
        public virtual IQueryable<F_NhanVienTheoMa_Result> F_NhanVienTheoMa(string ma)
        {
            var maParameter = ma != null ?
                new ObjectParameter("ma", ma) :
                new ObjectParameter("ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_NhanVienTheoMa_Result>("[BTH3Entities].[F_NhanVienTheoMa](@ma)", maParameter);
        }
    
        [DbFunction("BTH3Entities", "F_NhanVienTheoTen")]
        public virtual IQueryable<F_NhanVienTheoTen_Result> F_NhanVienTheoTen(string hoten)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_NhanVienTheoTen_Result>("[BTH3Entities].[F_NhanVienTheoTen](@hoten)", hotenParameter);
        }
    
        [DbFunction("BTH3Entities", "F_SoNhanVienTheoGT")]
        public virtual IQueryable<F_SoNhanVienTheoGT_Result> F_SoNhanVienTheoGT(string gt)
        {
            var gtParameter = gt != null ?
                new ObjectParameter("gt", gt) :
                new ObjectParameter("gt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_SoNhanVienTheoGT_Result>("[BTH3Entities].[F_SoNhanVienTheoGT](@gt)", gtParameter);
        }
    
        public virtual int SuaCong(string mact, string manv, Nullable<int> slngaycong)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var slngaycongParameter = slngaycong.HasValue ?
                new ObjectParameter("slngaycong", slngaycong) :
                new ObjectParameter("slngaycong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaCong", mactParameter, manvParameter, slngaycongParameter);
        }
    
        public virtual int SuaCT(string mact, string tenct, string diadiem, Nullable<System.DateTime> ngaycapgp, Nullable<System.DateTime> ngaykc)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var tenctParameter = tenct != null ?
                new ObjectParameter("tenct", tenct) :
                new ObjectParameter("tenct", typeof(string));
    
            var diadiemParameter = diadiem != null ?
                new ObjectParameter("diadiem", diadiem) :
                new ObjectParameter("diadiem", typeof(string));
    
            var ngaycapgpParameter = ngaycapgp.HasValue ?
                new ObjectParameter("ngaycapgp", ngaycapgp) :
                new ObjectParameter("ngaycapgp", typeof(System.DateTime));
    
            var ngaykcParameter = ngaykc.HasValue ?
                new ObjectParameter("ngaykc", ngaykc) :
                new ObjectParameter("ngaykc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaCT", mactParameter, tenctParameter, diadiemParameter, ngaycapgpParameter, ngaykcParameter);
        }
    
        public virtual int SuaNV(string manv, string hoten, Nullable<System.DateTime> ngaysinh, string gioitinh, string diachi, string mapb)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNV", manvParameter, hotenParameter, ngaysinhParameter, gioitinhParameter, diachiParameter, mapbParameter);
        }
    
        public virtual int SuaPB(string mapb, string tenpb)
        {
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaPB", mapbParameter, tenpbParameter);
        }
    
        public virtual int ThemCong(string mact, string manv, Nullable<int> slngaycong)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var slngaycongParameter = slngaycong.HasValue ?
                new ObjectParameter("slngaycong", slngaycong) :
                new ObjectParameter("slngaycong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemCong", mactParameter, manvParameter, slngaycongParameter);
        }
    
        public virtual int ThemCongTrinh(string mact, string tenct, string diadiem, Nullable<System.DateTime> ngaycapgp, Nullable<System.DateTime> ngaykc)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var tenctParameter = tenct != null ?
                new ObjectParameter("tenct", tenct) :
                new ObjectParameter("tenct", typeof(string));
    
            var diadiemParameter = diadiem != null ?
                new ObjectParameter("diadiem", diadiem) :
                new ObjectParameter("diadiem", typeof(string));
    
            var ngaycapgpParameter = ngaycapgp.HasValue ?
                new ObjectParameter("ngaycapgp", ngaycapgp) :
                new ObjectParameter("ngaycapgp", typeof(System.DateTime));
    
            var ngaykcParameter = ngaykc.HasValue ?
                new ObjectParameter("ngaykc", ngaykc) :
                new ObjectParameter("ngaykc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemCongTrinh", mactParameter, tenctParameter, diadiemParameter, ngaycapgpParameter, ngaykcParameter);
        }
    
        public virtual int ThemNV(string manv, string hoten, Nullable<System.DateTime> ngaysinh, string gioitinh, string diachi, string mapb)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNV", manvParameter, hotenParameter, ngaysinhParameter, gioitinhParameter, diachiParameter, mapbParameter);
        }
    
        public virtual int ThemPB(string mapb, string tenpb)
        {
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemPB", mapbParameter, tenpbParameter);
        }
    
        public virtual int XoaCong(string mact, string manv)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaCong", mactParameter, manvParameter);
        }
    
        public virtual int XoaCT(string mact)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaCT", mactParameter);
        }
    
        public virtual int XoaNV(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNV", manvParameter);
        }
    
        public virtual int XoaPB(string mapb)
        {
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaPB", mapbParameter);
        }
    }
}
